#!/bin/sh

# A post receive hook for updating the static webpage.

export LC_TYPE="en_US.UTF-8"

www="/var/www/git"
src="$(pwd)"
name=$(basename "$src")
dst="$www/$(basename "$name" '.git')"

[ ! -d dst ] && mkdir -p "$dst"
cd "$dst" || exit 1

stagit "$src"

ln -sf log.html index.html
ln -sf ../style.css style.css
ln -sf ../logo.png logo.png
